version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app

nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge
